force-app/main/default/objects/Test_Oppo_related__c/Test_Oppo_related__c.object-meta.xml
<CustomObject>
    <label>Test_Oppo_related</label>
    <nameField>
        <label>Test_Oppo_related Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test_Oppos_related</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Oppo_related__c/fields/Alignment_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Alignment_Effective_Date__c</fullName>
    <label>Alignment Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Test_Oppo_related__c/fields/Rebate_Eligibility_Field__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Eligibility_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rebate Eligibility Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Test_Oppo_related__c/fields/Rebate_Eligibility_Start__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Eligibility_Start__c</fullName>
    <label>Rebate Eligibility Start</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Immediately</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Oppo_related__c/fields/Rebate_Eligibility_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Eligibility_Start_Date__c</fullName>
    <label>Rebate Eligibility Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_Oppo_RelatedHandler.cls
public class Test_Oppo_RelatedHandler {
    public static void beforeInsertHandler(List<Test_Oppo_related__c> newList){
        for(Test_Oppo_related__c obj : newList ){
            if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Immediately' && obj.Alignment_Effective_Date__c !=null ){
                obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
            }
            else if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Monthly' && obj.Alignment_Effective_Date__c !=null ) {
                if(obj.Alignment_Effective_Date__c.month()<12){
                    obj.Rebate_Eligibility_Start_Date__c  = date.newInstance(obj.Alignment_Effective_Date__c.year(),obj.Alignment_Effective_Date__c.month()+1,01);
                }
                else if(obj.Alignment_Effective_Date__c.month() == 12) {
                    obj.Rebate_Eligibility_Start_Date__c  = date.newInstance(obj.Alignment_Effective_Date__c.year()+1, 01 ,01);   
                }
                if(obj.Alignment_Effective_Date__c.day() ==01 && obj.Alignment_Effective_Date__c.month() == (Date.today()).month()+1){
                    obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
                }
            }
            else if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Quarterly' && obj.Alignment_Effective_Date__c!=null){
                Date startDate = [Select StartDate from Period where Type = 'Quarter' and StartDate >: obj.Alignment_Effective_Date__c ORDER BY StartDate limit 1].StartDate;
                obj.Rebate_Eligibility_Start_Date__c = startDate;
                Date startDay = [Select StartDate, EndDate From Period where Type = 'Quarter' and StartDate = NEXT_FISCAL_QUARTER].StartDate;
                if(obj.Alignment_Effective_Date__c == startDay){
                    obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
            	}
            }
       }
    }
    public static void beforeUpdateHandler(List<Test_Oppo_related__c> newList, Map<Id,Test_Oppo_related__c> o){
        System.debug('Before Update Handler');
        for(Test_Oppo_related__c obj : newList){
        if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Immediately' && obj.Rebate_Eligibility_Start__c != o.get(obj.Id).Rebate_Eligibility_Start__c && obj.Alignment_Effective_Date__c !=null ){
            obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
        }
        else if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Monthly' && obj.Rebate_Eligibility_Start__c != o.get(obj.Id).Rebate_Eligibility_Start__c  && obj.Alignment_Effective_Date__c !=null ) {
            if(obj.Alignment_Effective_Date__c.month()<12){
                obj.Rebate_Eligibility_Start_Date__c  = date.newInstance(obj.Alignment_Effective_Date__c.year(),obj.Alignment_Effective_Date__c.month()+1,01);
            }
            else if(obj.Alignment_Effective_Date__c.month() == 12) {
                obj.Rebate_Eligibility_Start_Date__c  = date.newInstance(obj.Alignment_Effective_Date__c.year()+1, 01 ,01);   
            }
            if(obj.Alignment_Effective_Date__c.day() ==01 && obj.Alignment_Effective_Date__c.month() == (Date.today()).month()+1){
                obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
            }
        }
        else if(obj.Rebate_Eligibility_Field__c == true && obj.Rebate_Eligibility_Start__c == 'Quarterly' && obj.Rebate_Eligibility_Start__c != o.get(obj.Id).Rebate_Eligibility_Start__c  && obj.Alignment_Effective_Date__c!=null){
            Date startDate = [Select StartDate from Period where Type = 'Quarter' and StartDate >: obj.Alignment_Effective_Date__c ORDER BY StartDate limit 1].StartDate;
            obj.Rebate_Eligibility_Start_Date__c = startDate;
            Date startDay = [Select StartDate, EndDate From Period where Type = 'Quarter' and StartDate = NEXT_FISCAL_QUARTER].StartDate;
            if(obj.Alignment_Effective_Date__c == startDay){
                obj.Rebate_Eligibility_Start_Date__c = obj.Alignment_Effective_Date__c;
            }
        }
        }
    }
}